### ISSUE TITLE
Day 7 wrong pop method description

### ISSUE THREAD

**Issue by Mar1usSo** [Asabeneh/30-Days-Of-Python#124]
fruits.pop()  # removes the last element from the set

from the [doc](https://docs.python.org/2/library/sets.html#set-objects)
-->Remove and return an arbitrary element from the set. Raises KeyError if the set is empty.

**Comment by mariosanz97** [comment]
I have been looking this, and if you do a .pop on a set(), It always will delete the first element in the set.

Try with  this code:

`    fruits = {'banana0', 'orange1', 'mango2', 'mango3', 'mango4'}
    print(fruits)
    fruits.pop()
    print(fruits)
`

**Comment by ja153903** [comment]
I agree that the comment should be updated to match what Python docs state.

@mariosanz97 I believe the reason the set's `pop` function returns the first element is because under the hood sets are implemented as hash tables and it would be more performant to return the first element, but I don't think that this is behavior is guaranteed.
